GET http://localhost:5000/licence

###

GET http://localhost:5000/licence/SSN61a4e6a7ecf9b809ba4b69f0

###

POST http://localhost:5000/licence
Content-Type: application/json

{
    "first_name":"Himzo",
    "last_name":"Hodžić",
    "username":"programerAnel",
    "email":"programerAnel@gmail.com",
    "days":10
}

###

GET https://cryptotaxpeople.herokuapp.com/logs