GET http://localhost:5000/licence

###

DELETE http://localhost:5000/licence/deleteall

###

GET http://localhost:5000/licence/SSN61a4e6a7ecf9b809ba4b69f0

###

POST http://localhost:5000/licence
Content-Type: application/json

{
    "first_name":"Himzo",
    "last_name":"Hodžić",
    "username":"programerAnel",
    "email":"programerAnel@gmail.com",
    "days":"10"
}

###

POST http://localhost:5000/licence/activate
Content-Type: application/json

{
    "licence_key":"SSN61a544dd7f8acef894b0ec66",
    "computer_registered":"abc"
}